[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

# Disable package discovery since we're installing dependencies only
# https://github.com/pypa/setuptools/issues/3197
[tool.setuptools]
py-modules = []

[project]
name = "cellprofiler_plugins"
# description = "CellProfiler plugins"
readme = "README.md"
requires-python = ">=3.8,<3.10"
dynamic = ["version"]
dependencies = [
    # "cellprofiler",
    # "cellprofiler-core",
    "numpy"
]

[tool.setuptools.dynamic]
version = {attr = "0.1"}

[project.optional-dependencies]
cellpose = [
    "cellpose>=1.0.2"
]

