name: deploy-documentation

# Only run this when the master branch changes
on:
  push:
    branches:
    - master
    # Only run if edits in CP-plugins-documentation
    paths:
    - documentation/CP-plugins-documentation/**
    - .github/workflows/deploy.yml

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Install dependencies
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install jupyter-book

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build documentation/CP-plugins-documentation/

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./documentation/CP-plugins-documentation/_build/html
        cname: plugins.cellprofiler.org
