name: Install CellProfiler

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install CellProfiler dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-dev libgl1-mesa-glx

      - name: Install CellProfiler
        run: |
          pip install --upgrade pip setuptools wheel
          pip install numpy
          pip install cellprofiler

      - name: Verify installation
        run: |
          cellprofiler --version
