name: Install CellProfiler

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install CellProfiler dependencies
        run: |
          sudo apt-get update
          sudo apt install -y make gcc build-essential libgtk-3-dev
          sudo apt-get install -y python3-pip openjdk-11-jdk-headless default-libmysqlclient-dev libnotify-dev libsdl2-dev
          export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
          export PATH=$PATH:/home/ubuntu/.local/bin

      - name: Install CellProfiler
        run: |
          wget https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-20.04/wxPython-4.1.0-cp38-cp38-linux_x86_64.whl
          pip install wxPython-4.1.0-cp38-cp38-linux_x86_64.whl
          pip install --upgrade pip setuptools wheel
          pip install numpy
      - name: Install CellProfiler plugins
        run: |
          pip install -e .
      - name: Run plugin pipeline
        run: |
          python -m cellprofiler -c -r  --plugins-directory=. -p ./tests/headless_test/4.2.5_plugins_test_pipeline_BASIC.cppipe -i ./tests/headless_test/test_pipeline_img -o ./tests